version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - ./data:/var/lib/mysql
      - ./my_database.sql:/docker-entrypoint-initdb.d/my_database.sql
    ports:
      - "3306:3306"
    restart: always
