export enum CONSTANTS {
    USER_INACTIVE = 'User is inactive',
    USER_ALREADY_EXIST = 'User already exist with provided mail',
    USER_NOT_EXIST = 'User not exist',
    SOMETHING_WENT_WRONG_ERROR = 'Something went wrong',
    LOGIN_SUCCESS = 'Logged in successfully',
    REGISTER_SUCCESS = 'Registered successfully',
    EMAIL_VERIFIED = 'Email verified',
    INVALID_OTP = 'Invalid otp',
    OTP_EXPIRED = 'Otp expired',
    OTP_SENT = 'Otp has been sent on provided email',
    PASSWORD_CHANGED = 'Password has been changed',
    PASSWORD_MISMATCH = 'Password missmatched',
    BLOG_NOT_FOUND = 'Blog not found',
    BLOG_URL_CONFLICT = 'A blog with this thumbnail URL already exists.',
}
